/*  BEGIN_FILE_HDR
********************************************************************************
*   NOTICE                              
*   This software is the property of HiRain Technologies. Any information 
*   contained in this doc should not be reproduced, or used, or disclosed 
*   without the written authorization from HiRain Technologies.
********************************************************************************
*   File Name       : Dem_LCfg.c
********************************************************************************
*   Project/Product : AUTOSAR BSW PROJECT
*   Title           : Dem module configuration File
*   Author          : Hirain
********************************************************************************
*   Description     : Dem module configuration File
*
********************************************************************************
*   Limitations     : None
*
********************************************************************************
*
********************************************************************************
*   Revision History:
* 
*   Version     Date          Initials      CR#          Descriptions
*   ---------   ----------    ------------  ----------   ---------------
*   04.03.01    26/11/2016     Geno          N/A          N/A
*
********************************************************************************
* END_FILE_HDR*/

/*******************************************************************************
*   Include files
*******************************************************************************/
#include "Dem_Cfg.h"
#include "Dem_Types.h"
#include "Dem_Lcfg.h"
#include "Dem_Cbk.h"
/* -----------------------------------------------------------------------------
  Container Name : DemDTCClass
  This container contains the configuration (parameters) for DTCClass.
----------------------------------------------------------------------------- */
const Dem_DTCClassType DemDTCClassSet[DEM_NUMBER_OF_DTC] =
{
    {0xFE0010,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE000F,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE0012,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE0011,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE0030,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE002F,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE0050,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE004F,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE0072,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE0071,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE0090,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE008F,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE00B0,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE00AF,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE00D2,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE00D1,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE00F2,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE00F1,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE010B,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE0122,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE0140,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE0162,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE0182,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE01AB,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE01CB,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE01EB,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE020B,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE0230,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE022F,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE024B,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE026B,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE0290,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE028F,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE02A3,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE02A6,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE02A4,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE02E0,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE0300,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE0320,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE0340,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE02AA,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE02AB,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE02CB,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE02EA,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE030B,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE032B,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE034B,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE036B,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE038B,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE03AA,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE03CB,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE03EB,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE040B,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE042B,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE044B,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE046B,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE048B,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE04AB,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE04CA,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE04EB,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE050B,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE052B,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE054A,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE056B,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE058B,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE05AB,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE05CB,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE05C0,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE05EB,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE0610,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE060F,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR},
    {0xFE064B,0,DEM_DTC_SEV_NO_SEVERITY,FALSE,NULL_PTR}
};

const Dem_EventParameterType DemEventParameterTab[DEM_NUMBER_OF_EVENT] =
{
    {DEM_EVENT_KIND_SWC,0,0,0,0},
    {DEM_EVENT_KIND_SWC,0,1,0,0},
    {DEM_EVENT_KIND_SWC,0,2,0,0},
    {DEM_EVENT_KIND_SWC,0,3,0,0},
    {DEM_EVENT_KIND_SWC,0,4,0,0},
    {DEM_EVENT_KIND_SWC,0,5,0,0},
    {DEM_EVENT_KIND_SWC,0,6,0,0},
    {DEM_EVENT_KIND_SWC,0,7,0,0},
    {DEM_EVENT_KIND_SWC,0,8,0,0},
    {DEM_EVENT_KIND_SWC,0,9,0,0},
    {DEM_EVENT_KIND_SWC,0,10,0,0},
    {DEM_EVENT_KIND_SWC,0,11,0,0},
    {DEM_EVENT_KIND_SWC,0,12,0,0},
    {DEM_EVENT_KIND_SWC,0,13,0,0},
    {DEM_EVENT_KIND_SWC,0,14,0,0},
    {DEM_EVENT_KIND_SWC,0,15,0,0},
    {DEM_EVENT_KIND_SWC,0,16,0,0},
    {DEM_EVENT_KIND_SWC,0,17,0,0},
    {DEM_EVENT_KIND_SWC,0,18,0,0},
    {DEM_EVENT_KIND_SWC,0,19,0,0},
    {DEM_EVENT_KIND_SWC,0,20,0,0},
    {DEM_EVENT_KIND_SWC,0,21,0,0},
    {DEM_EVENT_KIND_SWC,0,22,0,0},
    {DEM_EVENT_KIND_SWC,0,23,0,0},
    {DEM_EVENT_KIND_SWC,0,24,0,0},
    {DEM_EVENT_KIND_SWC,0,25,0,0},
    {DEM_EVENT_KIND_SWC,0,26,0,0},
    {DEM_EVENT_KIND_SWC,0,27,0,0},
    {DEM_EVENT_KIND_SWC,0,28,0,0},
    {DEM_EVENT_KIND_SWC,0,29,0,0},
    {DEM_EVENT_KIND_SWC,0,30,0,0},
    {DEM_EVENT_KIND_SWC,0,31,0,0},
    {DEM_EVENT_KIND_SWC,0,32,0,0},
    {DEM_EVENT_KIND_SWC,0,33,0,0},
    {DEM_EVENT_KIND_SWC,0,34,0,0},
    {DEM_EVENT_KIND_SWC,0,35,0,0},
    {DEM_EVENT_KIND_SWC,0,36,0,0},
    {DEM_EVENT_KIND_SWC,0,37,0,0},
    {DEM_EVENT_KIND_SWC,0,38,0,0},
    {DEM_EVENT_KIND_SWC,0,39,0,0},
    {DEM_EVENT_KIND_SWC,0,40,0,0},
    {DEM_EVENT_KIND_SWC,0,41,0,0},
    {DEM_EVENT_KIND_SWC,0,42,0,0},
    {DEM_EVENT_KIND_SWC,0,43,0,0},
    {DEM_EVENT_KIND_SWC,0,44,0,0},
    {DEM_EVENT_KIND_SWC,0,45,0,0},
    {DEM_EVENT_KIND_SWC,0,46,0,0},
    {DEM_EVENT_KIND_SWC,0,47,0,0},
    {DEM_EVENT_KIND_SWC,0,48,0,0},
    {DEM_EVENT_KIND_SWC,0,49,0,0},
    {DEM_EVENT_KIND_SWC,0,50,0,0},
    {DEM_EVENT_KIND_SWC,0,51,0,0},    
    {DEM_EVENT_KIND_SWC,0,52,0,0},    
    {DEM_EVENT_KIND_SWC,0,53,0,0},    
    {DEM_EVENT_KIND_SWC,0,54,0,0},    
    {DEM_EVENT_KIND_SWC,0,55,0,0},    
    {DEM_EVENT_KIND_SWC,0,56,0,0},    
    {DEM_EVENT_KIND_SWC,0,57,0,0},    
    {DEM_EVENT_KIND_SWC,0,58,0,0},    
    {DEM_EVENT_KIND_SWC,0,59,0,0},    
    {DEM_EVENT_KIND_SWC,0,60,0,0},    
    {DEM_EVENT_KIND_SWC,0,61,0,0},    
    {DEM_EVENT_KIND_SWC,0,62,0,0},    
    {DEM_EVENT_KIND_SWC,0,63,0,0},    
    {DEM_EVENT_KIND_SWC,0,64,0,0},    
    {DEM_EVENT_KIND_SWC,0,65,0,0},    
    {DEM_EVENT_KIND_SWC,0,66,0,0},    
    {DEM_EVENT_KIND_SWC,0,67,0,0},    
    {DEM_EVENT_KIND_SWC,0,68,0,0},    
    {DEM_EVENT_KIND_SWC,0,69,0,0},
    {DEM_EVENT_KIND_SWC,0,70,0,0},
    {DEM_EVENT_KIND_SWC,0,71,0,0}
};
    
const Dem_EventClassType  DemEventClassSet[DEM_NUMBER_OF_EVENT]=
{
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0},   
    {TRUE,40,FALSE,DEM_DTC_ORIGIN_PRIMARY_MEMORY,1,1,DEM_EVENT_SIGNIFICANCE_FAULT,FALSE,DEM_OPCYC_IGNITION,0,DEM_OPCYC_IGNITION,DEM_OPCYC_IGNITION,0} 
};


void Dem_GetInternalDataElementFun
(
    Dem_InternalDataElementType InteElemType,uint8* Buffer
)
{

}

union
{
    uint8  _c[4];
    uint32 Example0;
}DemExternalSRDemo;
/********************All DataElementClass def**********************************/
const Dem_InternalDataElementClassType DemInternalDataElementClassTab[] =
{
    {1,DEM_OCCCTR},
    {1,DEM_PENDINFCTR},
    {1,DEM_AGEDCTR},
    {1,DEM_AGINGCTR},
};

const Dem_ExternalCSDataElementClassType Dem_ExternalCSDataElementClassTab[]=
{
    {5,Dem_ReadDataElementFun_0xfd8b}, /*故障发生时间*/
    {5,Dem_ReadDataElementFun_0xfd8c}, /*故障停止时间*/    
    {2,Dem_ReadDataElementFun_0xfd74}, /*总电流*/
    {2,Dem_ReadDataElementFun_0xfd75}, /*总电压*/
    {2,Dem_ReadDataElementFun_0xfd76}, /*单体最高电压*/
    {2,Dem_ReadDataElementFun_0xfd77}, /*单体最低电压*/
    {2,Dem_ReadDataElementFun_0xfd78}  /*最高温度*/

};

const Dem_ExternalSRDataElementClassType Dem_ExternalSRDataElementClassTab[]=
{
    {4,DemExternalSRDemo._c}
};

/***************FF*******************/
const Dem_DidClassType DemDidClassTab0[]=
{
    {0xfd8B,DemExternalCS,0}, /*故障发生时间*/
    {0xfd8C,DemExternalCS,1}, /*故障停止时间*/
    {0xfd74,DemExternalCS,2}, /*总电流*/
    {0xfd75,DemExternalCS,3}, /*总电压*/
    {0xfd76,DemExternalCS,4}, /*单体最高电压*/
    {0xfd77,DemExternalCS,5}, /*单体最低电压*/
    {0xfd78,DemExternalCS,6}  /*最高温度*/
    
};
const Dem_FreezeFrameRecNumClassType DemFreezeFrameRecNumClassTab0[] =
{
    {1 ,7,&DemDidClassTab0[0]},
};

const Dem_FreezeFrameClassType DemFreezeFrameClassTab0[] =
{
    {1,&DemFreezeFrameRecNumClassTab0[0]}
};
/************extended data**************/
const Dem_ExtendedDataElementType DemExtendedDataElemen0[]=
{
    {DemInternal,0},
    {DemInternal,1},
    {DemInternal,2},
    {DemInternal,3},
};
/*
const Dem_ExtendedDataElementType DemExtendedDataElemen1[2]=
{
    {DemExternalCS,14},
    {DemExternalCS,15},
};
*/
const Dem_ExtendedDataRecordClassType DemExtendedDataRecordClassTab0[] =
{
    {1,DEM_UPDATE_RECORD_YES,4,&DemExtendedDataElemen0[0]},
    /*{2,DEM_UPDATE_RECORD_YES,2,&DemExtendedDataElemen1[0]}*/
};
const Dem_ExtendedDataClassType DemExtendedDataClassTab0[]=
{
    {1,&DemExtendedDataRecordClassTab0[0]}
};
/**********Dem_DebounceAlgorithmClassType*******/

const Dem_DebounceAlgorithmClassType DemDebounceAlgorithmClassTab[DEM_NUMBER_OF_EVENT] =
{
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}},
    {{-3,5,-30,30,TRUE,TRUE,0,0},{3000,3000},{NULL_PTR},{0}}
};




